name: Win10RDP!

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Downloading Ngrok and Start Script
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/msraj1584/msrajserv/main/start.bat -OutFile start.bat

    - name: Extracting Ngrok Files
      run: Expand-Archive ngrok.zip

    - name: Verify Ngrok Version
      run: ngrok\ngrok.exe version
      shell: cmd

    - name: Connecting to Ngrok Account
      run: ngrok\ngrok.exe config add-authtoken 2825WqcznOwL6RC7bGsjecu1ztF_6D87h96jFdRhpUJ69m8TN
      shell: cmd

    - name: List Local User Accounts
      run: Get-LocalUser | Select-Object Name
      shell: pwsh

    - name: Enable Administrator Account (PowerShell)
      run: |
        $adminAccount = Get-LocalUser | Where-Object { $_.Name -eq "Administrator" }
        if ($adminAccount -eq $null) {
          Write-Host "Administrator account does not exist."
        } else {
          Enable-LocalUser -Name "Administrator"
        }
      shell: pwsh

    - name: Add User to Remote Desktop Users Group
      run: |
        # Try adding 'Administrator' if found, otherwise fallback to a user like 'runneradmin'
        $user = Get-LocalUser | Where-Object { $_.Name -match "admin" }
        if ($user) {
          net localgroup "Remote Desktop Users" $user.Name /add
          Write-Host "$($user.Name) added to the Remote Desktop Users group."
        } else {
          Write-Host "No matching admin user found"
        }
      shell: pwsh

    - name: Activating RDP Access
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
      shell: pwsh

    - name: Creating Ngrok Tunnel with Debug Logging
      run: ngrok\ngrok.exe tcp 3389 --log=stdout --log-level=debug
      shell: cmd

    - name: Display Ngrok Tunnel URL
      run: |
        $log = Get-Content ngrok_log.txt
        $url = ($log | Select-String -Pattern "url=tcp://").Matches.Value
        Write-Host "========================================"
        Write-Host "Ngrok Tunnel is Ready!"
        Write-Host "Connect using this URL: $url"
        Write-Host "Username: administrator"
        Write-Host "Password: 9S8a7r6a5n"
        Write-Host "========================================"
      shell: pwsh

    - name: Keep RDP Running
      run: cmd /c start.bat
