name: Win10RDP11

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Downloading Ngrok and Start Script
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/msraj1584/msrajserv/main/start.bat -OutFile start.bat

    - name: Extracting Ngrok Files
      run: Expand-Archive ngrok.zip

    - name: Verify Ngrok Version
      run: .\ngrok\ngrok.exe version

    - name: Connecting to your Ngrok account
      run: .\ngrok\ngrok.exe authtoken 2825WqcznOwL6RC7bGsjecu1ztF_6D87h96jFdRhpUJ69m8TN

    - name: Enable Administrator Account and Set Password
      run: |
        net user administrator /active:yes
        net user administrator 9S8a7r6a5n
      shell: cmd

    - name: Allow Administrator to Access RDP
      run: net localgroup "Remote Desktop Users" administrator /add
      shell: cmd

    - name: Activating RDP Access
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Creating Ngrok Tunnel
      shell: cmd
      run: ngrok\ngrok.exe tcp 3389 --log=stdout > ngrok_log.txt

    - name: Display Ngrok Tunnel URL
      run: |
        $log = Get-Content ngrok_log.txt
        $url = ($log | Select-String -Pattern "url=tcp://").Matches.Value
        Write-Host "========================================"
        Write-Host "Ngrok Tunnel is Ready!"
        Write-Host "Connect using this URL: $url"
        Write-Host "Username: administrator"
        Write-Host "Password: 9S8a7r6a5n"
        Write-Host "========================================"
      shell: pwsh

    - name: Connecting to your RDP
      run: cmd /c start.bat

    - name: RDP is Ready
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/msraj1584/msrajserv/main/loop.ps1 -OutFile loop.ps1
        ./loop.ps1
